version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Random pass/fail"
          command: |
            echo "Failing this run."
            exit 1

  waiter:
    docker:
      - image: cimg/base:current
    steps:
      - run: |
          until [[ $(curl --location --request GET "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job" --header "Circle-Token: $CCI_TOKEN"| jq -r '.items[]|select(.name == "say-hello" or .name == "approve-manual")|.status' | grep -c "success") -gt 0 ]]; do
            sleep 1
          done

  gate:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: "Final gate"
          command: |
            echo "Gate passed."

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - approve-manual:
          type: approval
          requires:
            - say-hello: failed
      - waiter
      - gate:
          requires:
            - waiter
