name: Always Pass

on:
  push:
  pull_request:

jobs:
  pass:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "All good"
  pass-2:
    runs-on: ubuntu-latest
    steps:
      - name: Another no-op
        run: echo "Still good"
